linters-settings:
  golint:
    min-confidence: 0

  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - typecheck
    - goimports
    - misspell
    - govet
    - golint
    - ineffassign
    - gosimple
    - deadcode
    - structcheck
    - gomodguard
    - gofmt

issues:
  exclude-use-default: false
  exclude:
      - should have a package comment
      - error strings should not be capitalized or end with punctuation or a newline

run:
  skip-dirs:
    - pkg/rpc
    - pkg/argon2

service:
  golangci-lint-version: 1.20.0 # use the fixed version to not introduce new linters unexpectedly
